### PR TITLE
Fix for github issue #1 update to get the pending ID and violation count

### PR DESCRIPTION
**Pull request by psantos1113**
Change the SDK calls being used to traverse the node tree in order to
calculate the count of the pending IDs and Violations.  The previous
mechanism to use the root node and have the SDK aggregate the
information does not work with Protex 7.4.

### CODE REVIEW

**Comment by psantos1113** [comment]
@stevebillings When you get a chance can you please review.  This is similar to the code changes in common framework.

**Comment by stevebillings** [comment]
Hi Paulo:

github is showing every line in ProtexFacade as changed. Were the changes that extensive, or are formatting differences making it look more extensive than it was. (If the changes were smaller, I'm hoping you can direct me toward the actual changes).

Thanks,
Steve

**Comment by psantos1113** [comment]
Hi Steve,

The changes are formatting changes mostly.  The actual code changes are in 3 methods.  The majority of the changes are in the getTreeNodes method, getPendingIds, and getViolationCount methods.  I will discuss the changes with you.

**Comment by stevebillings** [comment]
Looks good.

**Pull request merged**
